### ISSUE TITLE
using different line type 

### ISSUE THREAD

**Issue by mguller** [dreamRs/billboarder#13]
Hi,
I would like to ask two questions:
- How can we use two different line type for multiline graph. I want to use dashed line for one data, and normal line for other one.  
- I also want to use different width for each line but I could not find an example.

I would be so appreciate if you can help about this two issues.

Thank you in advance

**Comment by pvictor** [comment]
Hi,
There no trivial option to do that in CRAN version, I added two arguments to `bb_linechart()` to do so.
You can find examples here : https://dreamrs.github.io/billboarder/articles/lines-options.html

Victor
