### ISSUE TITLE
updated billboarder 2.7

### ISSUE THREAD

**Issue by mguller** [dreamRs/billboarder#14]
Hi,

First of all, i  would like to thank for a this great package and your answer for my previous question.
I was using billboarder 2.5 and today updated 2.7. 
After updating, all my program started not to work. I cannot see any figure or graph but it does not give any error. It just shows empty figure

What can be the problem?

Thank you in advance

**Comment by pvictor** [comment]
Hello,
Can you provide an example where it don't work ? so that I can reproduce the problem.
And cou include the result of `sessioninfo::session_info()` ?

Thank you,

Victor

**Comment by pvictor** [comment]
And are you using Internet Explorer ?

**Comment by mguller** [comment]
I am using RStudio and Shiny.
I downloaded billboarder from install.packages("billboarder").  This is the session info:
- Session info ------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.2 (2018-12-20)
 os       Windows >= 8 x64            
 system   i386, mingw32               
 ui       RStudio                     
 language (EN)                        
 collate  German_Germany.1252         
 ctype    German_Germany.1252         
 tz       Europe/Berlin               
 date     2019-10-15 

I created "wide" data frame as you described here and then used
billboarder()%>%bb_linechart(data = wide, type = "line")

but it does not show anything at "viewer" tab at RStudio

**Comment by pvictor** [comment]
Can you install the dev version and see if it's better ? 
To install dev version : 
```r
devtools::install_github("dreamRs/billboarder")
```

**Comment by mguller** [comment]
I guess the problem is that I am using R 3.5.2 and when I run shiny it says:

Warning: Packet ‘billboarder’ is created under R Version 3.5.3.
This version of Shiny is designed to work with 'htmlwidgets' >= 1.5.
    Please upgrade via install.packages('htmlwidgets')

can R Version be reason of problem?

Thank you for your support

**Comment by pvictor** [comment]
Have you tried to update htmlwidgets, then billboarder ?

```
install.packages('htmlwidgets')
devtools::install_github("dreamRs/billboarder")
```

I recommend you to do that in a fresh R session (close RStudio and reopen), then try again to make some charts.

**Comment by pro100mir** [comment]
Dear Victor,

Updating in this order, as you indicated, resolved the issue. Works like a charm!! I noticed that version is now 0.2.7.960. 
Now everything is working again both in Rstudio viewer and Shiny app. 

Thanks a lot!!!
Mircea

**Comment by pvictor** [comment]
Hello Musatafa,
Welcome to R 🎉 , never easy to start a new language.
It's ok to have two paths for packages installed.
The message 
```
The following objects are masked from ‘package:billboarder’:
prefix, suffix
```
indicate that several packages have functions with the same name, you just have to be careful when using them. For example : 

```r
dplyr::select
stats::select
```
are two different functions.

Have you tried to close RStudio (all of them) reopen it, then write into the console : 

```r
devtools::install_github("dreamRs/billboarder")
```
?
Can you send the full result of `sessioninfo::session_info()` ? (after trying to make some charts)

Victor

**Comment by mguller** [comment]
Hi Victor,
When I try to use devtools::install_github("dreamRs/billboarder"), I get this message:
WARNING: Rtools is required to build R packages, but is not currently installed.
Please download and install Rtools custom from http://cran.r-project.org/bin/windows/Rtools/.

I will try to download Rtools and try again, if it helps. But I downloaded billboarder from CRAN at other laptop, and it worked. only I could not draw dash lines or use different width, these functions did not work. At my laptop, session_info is:
- Session info --------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.2 (2018-12-20)
 os       Windows >= 8 x64            
 system   i386, mingw32               
 ui       RStudio                     
 language (EN) 

- Packages --------------------------------------------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.0   2017-04-11 [1] CRAN (R 3.5.2)
 billboarder * 0.2.7   2019-08-21 [1] CRAN (R 3.5.3)
 cli           1.1.0   2019-03-19 [1] CRAN (R 3.5.3)
 colorspace    1.4-0   2019-01-13 [1] CRAN (R 3.5.2)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.2)
 digest        0.6.18  2018-10-10 [1] CRAN (R 3.5.2)
 dplyr         0.8.3   2019-07-04 [1] CRAN (R 3.5.3)
 ggplot2       3.1.0   2018-10-25 [1] CRAN (R 3.5.2)
 glue          1.3.0   2018-07-17 [1] CRAN (R 3.5.2)
 gtable        0.2.0   2016-02-26 [1] CRAN (R 3.5.2)
 htmltools     0.4.0   2019-10-04 [1] CRAN (R 3.5.3)
 htmlwidgets   1.5.1   2019-10-08 [1] CRAN (R 3.5.3)
 jsonlite      1.6     2018-12-07 [1] CRAN (R 3.5.2)
 lazyeval      0.2.1   2017-10-29 [1] CRAN (R 3.5.2)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.2)
 munsell       0.5.0   2018-06-12 [1] CRAN (R 3.5.2)
 pillar        1.3.1   2018-12-15 [1] CRAN (R 3.5.2)
 pkgconfig     2.0.2   2018-08-16 [1] CRAN (R 3.5.2)
 plyr          1.8.4   2016-06-08 [1] CRAN (R 3.5.2)
 purrr         0.3.1   2019-03-03 [1] CRAN (R 3.5.2)
 R6            2.4.0   2019-02-14 [1] CRAN (R 3.5.2)
 Rcpp          1.0.2   2019-07-25 [1] CRAN (R 3.5.3)
 rlang         0.4.0   2019-06-25 [1] CRAN (R 3.5.3)
 rstudioapi    0.9.0   2019-01-09 [1] CRAN (R 3.5.2)
 scales        1.0.0   2018-08-09 [1] CRAN (R 3.5.2)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.2)
 tibble        2.1.3   2019-06-06 [1] CRAN (R 3.5.3)
 tidyselect    0.2.5   2018-10-11 [1] CRAN (R 3.5.2)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.2)
 yaml          2.2.0   2018-07-25 [1] CRAN (R 3.5.2)

Is there difference download from CRAN or devtools?

Thank you for your help. I like billboarder package and do not want to start with other packages :)

**Comment by pro100mir** [comment]
Hi Victor,

How can I use the new dashes and line width with the rawAPI? 
Btw, you are doing a great job!

Thank you,
Mircea

**Comment by mguller** [comment]
Hi Victor,

After updating rstudio and R, now it is working again. But dashes and line width functions for line graph are not working. What can be reason?

Thank you
