### ISSUE TITLE
Tooltip does not appear when linked between charts

### ISSUE THREAD

**Issue by DKBurns** [dreamRs/billboarder#15]
Hello DreamRs team,

Thank you for putting together this wonderful package, it is very nice, especially when used in a `Shiny` app. Whilst trying to learn how to use this package effectively, I came across the example provided by your team showing linked tooltips (located [here](https://gist.github.com/pvictor/49fdb05d362acca8d6b94d69345a5046)) 

Unfortunately, this does not appear to work, either inside of a shiny app or when just using the defined `make_line()` function. When using the code as it is now, all of the graphs produced do not have visible tooltips (either in Rstudio 1.2.5.001 viewer or Firefox 71.0, each with R 3.6.1, MS Windows 10).

When editing the code to put a scatterplot on top of the linechart, the vertical line appears when hovering over a point, but *not* the tooltip:

```R
# on CRAN now (version 0.2.3)
library(billboarder)

# data
data("economics", package = "ggplot2")

# helper fun
make_line <- function(var, title, percent = TRUE) {
  billboarder() %>%
    bb_linechart(data = economics[, c("date", var)]) %>%
    bb_scatterplot(data = economics[, c("date", var)]) %>%
    bb_x_axis(tick = list(format = "%Y-%m", fit = FALSE)) %>%
    bb_y_axis(tick = list(format = if (percent) suffix("%"))) %>%
    bb_legend(show = TRUE) %>%
    bb_x_grid(show = TRUE) %>%
    bb_y_grid(show = TRUE) %>%
    bb_labs(title = title) %>%
    bb_tooltip(linked = list(name = "my-tooltip")) # <--- Id for linking tooltip
}
make_line("psavert", "Personal savings rate", TRUE)
make_line("uempmed", "Number of unemployed", TRUE)
make_line("pce", "Personal consumption expenditures", FALSE)
make_line("pop", "Total population", FALSE)
```

I also noticed that when doing a simple un-linked `bb_linechart()` with some example data, the tooltip does not appear either, and I have to put a `bb_scatterplot()` subsequent to the `bb_linechart` to make it appear.

I hope this is not too much of a nightmare to resolve, as those tooltips are extremely useful within a `Shiny` app.

Thanks again for making this package, it is very nice and I eagerly look forward to future updates!

Darren

**Comment by pvictor** [comment]
Ouch there's indeed a bug with CRAN version... Try install from GitHub see if it works : 

```r
devtools::install_github("dreamRs/billboarder")
```

You can also look at this vignette, see if it renders properly in Firefox (works for me with same version) : https://dreamrs.github.io/billboarder/articles/linked-tooltip.html

Victor

**Comment by DKBurns** [comment]
Hi Victor,

Thanks for getting back to me so quickly. Yes, installing from github leads to the tooltips appearing as expected!

That vignette does render correctly on the site. However, if you follow the link at the top and paste the raw into a script with the current CRAN version of billboarder, it still doesn't work. Does this mean that the vignette was rendered using a later version of billboarder?

I take it that this bug fix will be included in the next CRAN release of billboarder? Do you guys have a schedule planned for that, or for the time being should I include some code to install billboarder from github if the version is less than `v0.2.7.970` for my existing projects?

Thanks again!

**Comment by pvictor** [comment]
Yes, we plan to release a new version within a week or two.
