### ISSUE TITLE
Lower part of caption is cut

### ISSUE THREAD

**Issue by newuserofthis** [dreamRs/billboarder#17]
Dear billboarder team,

thanks for your wonderful R package. I have a minor problem with the display of a chart's caption. The lower part of it is missing. I added `bb_opts = list(padding = list(bottom=100))` as argument to the `billboarder()` function. It works but gets overwritten when the `bb_labs()` function is called with a caption argument.
How can the bottom margin be enlarged after calling the `bb_labs()` function? Or is there another way of displaying the caption entirely. Thanks for your help!

Anja

```R
library("billboarder")

# data
data("prod_par_filiere")

# a bar chart !
billboarder() %>%
  bb_barchart(data = prod_par_filiere[, c("annee", "prod_hydraulique")], color = "#102246") %>%
  bb_y_grid(show = TRUE) %>%
  bb_y_axis(tick = list(format = suffix("TWh")),
            label = list(text = "production (in terawatt-hours)", position = "outer-top")) %>% 
  bb_legend(show = FALSE) %>% 
  bb_labs(title = "French hydraulic production",
          caption = "gqpjy: RTE (https://opendata.rte-france.com)")
```

**Comment by pvictor** [comment]
Hello,

Thanks for reporting this, it should be fixed:

![image](https://user-images.githubusercontent.com/4415580/82203523-b9d64380-9903-11ea-9497-dea17f272eea.png)

I also added ar argument to use caption as a link.

Please install from GitHub to have latest version, I'll submit to CRAN soon.

Victor

**Comment by newuserofthis** [comment]
Thank you for the quick fix, Victor! Works like a charm!

Best wishes
Anja
