### ISSUE TITLE
Scatterplot with region & custom tooltip

### ISSUE THREAD

**Issue by rsangole** [dreamRs/billboarder#22]
Hello,

I'm wondering if it's possible to create a `billboarder` equivalent to this `plot_ly` plot:

```r
library(plotly)

plotly::plot_ly(
  data = mtcars,
  x = ~ mpg,
  y = ~ disp,
  type = "scatter",
  color = ~ as.factor(cyl),
  hoverinfo = "text",
  hovertemplate = ~ glue::glue("<b>Cyl: {grp}</b>
                               mpg: {x}, disp: {y}", grp = cyl, x = mpg, y = disp)
) %>%
  plotly::layout(shapes = list(
    list(
      type = "rect",
      fillcolor = "red",
      line = list(color = "red"),
      opacity = 0.1,
      x0 = "10",
      x1 = "20",
      xref = "x",
      y0 = 30,
      y1 = 350,
      yref = "y"
    )
  ))
```

<img width="657" alt="image" src="https://user-images.githubusercontent.com/6344050/98199921-37593480-1ee1-11eb-8507-4757705d0f72.png">

**Comment by pvictor** [comment]
Not currently I'm afraid... The rectangle annotation is not supported in main library, there's a plugin that should allow to do it but I've never used it...
