### ISSUE TITLE
Hover Possible?

### ISSUE THREAD

**Issue by rsangole** [dreamRs/billboarder#24]
Like you have in your example for `click`

```r
output$click <- renderPrint({
    cat("# input$mybbchart_click$category", "\n")
    input$mybbchart_click$category
  })
```

I couldn't get "hover" to work using something like `input$mybbchart_hover$category`. Is this something that's possible? Which Shiny events are currently supported?

**Comment by rsangole** [comment]
Thanks @pvictor . This worked perfectly.

Followup Q:

Is it possible to detect a click on a barchart when the user isn't ON the bar? My use case is highly skewed data like this:

![image](https://user-images.githubusercontent.com/6344050/101358590-e924b180-384f-11eb-82fb-c0bfa647207e.png)

You can see where the user's mouse is currently placed. It's intuitive for the user to simply click right where the mouse is... It's not intuitive for the user to have to move the mouse OVER the bar and then click. This is causing some UX frustration.

Any ideas?

**Comment by pvictor** [comment]
Hello,

As far as I know it's not possible to retrieve click information without clicking the data object...

Here's an example for fixed tooltip if you want to try (you have to use some HTML to format content):

```r
library(shiny)
library(billboarder)
data("economics_long", package = "ggplot2")



ui <- fluidPage(
  tags$h2("Fixed tooltip"),
  fluidRow(
    column(
      width = 8,
      billboarderOutput("mychart")
    ),
    column(
      width = 4,
      tags$div(id = "mytooltip")
    )
  )
)

server <- function(input, output, session) {
  
  output$mychart <- renderBillboarder({
    billboarder(data = economics_long) %>% 
      bb_linechart(
        mapping = bbaes(x = date, y = value01, group = variable)
      ) %>% 
      bb_x_axis(tick = list(fit = FALSE)) %>% 
      bb_tooltip(
        init = list(
          show = TRUE
        ),
        doNotHide = TRUE,
        contents = list(
          bindto = "#mytooltip",
          template = "<ul><li>Index<br>{=TITLE}</li>{{<li class={=CLASS_TOOLTIP_NAME}><span>{=VALUE}</span><br><span style=color:{=COLOR}>{=NAME}</span></li>}}</ul>"
        )
      )
  })
  
}

shinyApp(ui, server)
```

**Comment by rsangole** [comment]
Thanks @pvictor. This was very helpful. Perhaps you could include this full example in `bb_tooltip`, for folks like me who don't know html & css as much?
