### ISSUE TITLE
bb_gauge complete circle 

### ISSUE THREAD

**Issue by uttam-1996** [dreamRs/billboarder#7]
can you help me out how can i get a complete circle gauge chart ?
     

`billboarder()%>%
      bb_gaugechart(num)
![Rplot](https://user-images.githubusercontent.com/33053682/58858716-cdbe7080-86c5-11e9-89c1-edf0579b0767.png)

but i want a full circle gauge chart
`

**Comment by pvictor** [comment]
Hi,

You can use : 

```r
library(billboarder)
billboarder()%>%
  bb_gaugechart(57) %>% 
  bb_gauge(fullCircle = TRUE)
```

You can find JavaScript examples here https://naver.github.io/billboard.js/demo/#GaugeChartOptions.GaugeFullCircle to adapt to your R code.

This is also possible in the last release with : 

```r
bauge(value = 57, full_circle = TRUE)
```

Victor

**Comment by uttam-1996** [comment]
Thank you :+1:
